apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static #pv volume name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi