apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "ebs-sc" #storage class name
  resources:
    requests:
      storage: 19Gi