apiVersion: v1
kind: Pod
metadata:
  name: labels      #these are labels for a pod
  labels:
    project: expense
    environment: dev
    component: backend
spec:
  containers:
  - name: nginx
    image: nginx