apiVersion: v1
kind: Pod
metadata:
  name: annotations      #these are annotations for a pod
  annotations:
    buildURL: "https://jenkins.com/expense/job/backend/23"
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx